server:
  port: 8081

spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/spring-security?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root

# mybatis
mybatis:
  configuration:
    mapUnderscoreToCamelCase: true
    use-generated-keys: true